include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_final_parameters: false
    avoid_slow_async_io: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    flutter_style_todos: false

analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
  # plugins:
  #   - custom_lint
